### ISSUE TITLE
Fix addEnhancedEcommerceProductContext setting product list to null

### ISSUE THREAD

**Issue by volderette** [snowplow/snowplow-gtm-custom-template#16]
In addEnhancedEcommerceProductContext, the list field is set to null, when there is no product list defined in the datalayer. However, the Snowplow schema doesn't allow null, but only strings:

https://github.com/snowplow/snowplow-gtm-custom-template/blob/e3e18e7ede271060deeb33e4d54172d6ff40eb3d/template.tpl#L1602

I'm not sure what the best option would be in that case?

**Comment by paulboocock** [comment]
Good spot. This method directly populates https://github.com/snowplow/iglu-central/blob/master/schemas/com.google.analytics.enhanced-ecommerce/productFieldObject/jsonschema/1-0-0#L22 which doesn't accept nulls.

This will need updating to:
`obj[a].actionField ? obj[a].actionField.list : '',`

**Comment by sahava** [comment]
Thank you so much @volderette - updated the PR to fix this as well.
