### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [snowplow/snowplow-gtm-custom-template#7]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1. User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template.
2. The documentation [url](https://www.simoahava.com/custom-templates/snowplow-analytics/) shows "Page not found" error.
![Screenshot 2020-05-14 at 10 48 23 AM](https://user-images.githubusercontent.com/53495700/81968594-7319de00-95d1-11ea-9c0c-404bd9ab2d93.png)

**Comment by paulboocock** [comment]
Thank you. The documentation URLs and installation instructions are now fixed. 
We'll continue to update the installation documentation to ensure it follows these rules.
Thank you for the feedback.
